### ISSUE TITLE
Feature: Login und Registrierung

### ISSUE THREAD

**Issue by webanwendung-on18** [webanwendung-on18/effective-octo-waffle#2]
# Description
Implementierung der Authentifizierung mit Hilfe von Firebase.

# Definition of done
* Routes: `/login`, `/register` funktionieren
* Routes sind sicher implementiert
* Passwörter werden sicher gehashed und abgelegt
* Login / Registrierungs -Maske ist implentiert und gestyled

# Additional Information / Links
Siehe auch [Tumblr-Login](https://tumblr.com)

**Comment by eisenils** [comment]
Profilbild fehlt noch bei Registrierung
